//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceTest.DEV1Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DEV1Service.IDEV1Service")]
    public interface IDEV1Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDEV1Service/GetBurnDownData", ReplyAction="http://tempuri.org/IDEV1Service/GetBurnDownDataResponse")]
        string GetBurnDownData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDEV1Service/GetBurnDownData", ReplyAction="http://tempuri.org/IDEV1Service/GetBurnDownDataResponse")]
        System.Threading.Tasks.Task<string> GetBurnDownDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDEV1ServiceChannel : WCFServiceTest.DEV1Service.IDEV1Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DEV1ServiceClient : System.ServiceModel.ClientBase<WCFServiceTest.DEV1Service.IDEV1Service>, WCFServiceTest.DEV1Service.IDEV1Service {
        
        public DEV1ServiceClient() {
        }
        
        public DEV1ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DEV1ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DEV1ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DEV1ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetBurnDownData() {
            return base.Channel.GetBurnDownData();
        }
        
        public System.Threading.Tasks.Task<string> GetBurnDownDataAsync() {
            return base.Channel.GetBurnDownDataAsync();
        }
    }
}
